### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by wish-1996** [Xuanfang1121/gpt3_text_generation_chinese#1]
你好，能提供一下数据集我去跑一下试试嘛，感谢

**Comment by Xuanfang1121** [comment]
hi，请查收
















在 2023-03-15 19:43:12，"wish-1996" ***@***.***> 写道：

你好，能提供一下数据集我去跑一下试试嘛，感谢

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

从网易163邮箱发来的超大附件推荐客户端极速下载
train.txt (41.77M, 2023年4月24日 12:07 到期)
下载
test.txt (204.96K, 2023年4月24日 12:07 到期)
在线预览 | 下载

**Comment by fgghhsha123** [comment]
> 你好，能提供一下数据集我去跑一下试试嘛，感谢

您好！能提供一下数据集给我也去跑一下试试嘛
